### ISSUE TITLE
Files missing in Linux release?

### ISSUE THREAD

**Issue by asteppke** [jdegenstein/jmwright-CQ-Editor#16]
I wanted to try out the Linux release (CQ-Editor 0.30-dev-3) and downloaded the corresponding `.zip` file. When trying to run the editor I got immediate errors because of missing Qt libraries. 

A quick look into the file revealed that there are a rather large number of empty files:

![image](https://github.com/jdegenstein/jmwright-CQ-Editor/assets/5851636/637a07e5-bda5-41cd-921a-1f37e0d98033)

Is there an error with the build process?

**Comment by jdegenstein** [comment]
Sorry for the slow response. I was able to take a look and there is indeed a problem but the real problem is missing symlinks. I haven't had a chance to fix it, but in the meantime I run weekly builds automatically. You can just use those, and this problem should not be present. https://github.com/jdegenstein/jmwright-CQ-Editor/actions/runs/7689743989

**Comment by jdegenstein** [comment]
@asteppke I published a new release that should fix this issue here: https://github.com/jdegenstein/jmwright-CQ-Editor/releases/tag/0.30-dev-4

Could you test it out and check?

**Comment by jdegenstein** [comment]
Closing this issue since I have not heard back and I believe it is fixed. Feel free to reopen if that is not true.
