### ISSUE TITLE
build123d v0.6

### ISSUE THREAD

**Issue by BlueDrink9** [jdegenstein/jmwright-CQ-Editor#21]
The latest release no longer has the latest [build123d version](https://github.com/gumyr/build123d/releases/tag/v0.6.0)

**Comment by jdegenstein** [comment]
Thanks for reporting, yes I am aware. You can always download the latest builds from the actions tabs, and here is the most recent one --https://github.com/jdegenstein/jmwright-CQ-Editor/actions/runs/10764277824

I need to find time to work on the MacOS builds because there are some issues with giving them some type of security attribute.

**Comment by BlueDrink9** [comment]
Good to know about the actions builds!

Someone also mentioned the option to use the bundled python on windows to update b123d, but I can't figure that out on linux

**Comment by jdegenstein** [comment]
Closing this as I just published a new release that includes build123d==0.7.0 here https://github.com/jdegenstein/jmwright-CQ-Editor/releases
